# Site settings
title: KUMI
email: elijah8512@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  ProjectKumi Photography & Videography
baseurl: "/projectkumi" # the subpath of your site, e.g. /blog
url: " kidnplaykumi.github.io" # the base hostname & protocol for your site
twitter_username: projectkumi
github_username:  projectkumi

# Build settings
markdown: kramdown
permalink: pretty
